name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update --remote --recursive

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-11-2
          echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
          echo "PATH=/usr/local/cuda/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          export CUDA_HOME=/usr/local/cuda
          export PATH=/usr/local/cuda/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

      - name: Verify CUDA installation
        run: |
          nvcc --version
          which nvcc
          ls -l $CUDA_HOME

      - name: Run tests
        run: |
          pytest tests/ --cov=agents --cov=workflows

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
