name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1.1-base-ubuntu22.04  # 使用NVIDIA CUDA镜像
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 仅需私有仓库时添加

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch==2.6.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/
